services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    container_name: avilaTek_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  avila-app:
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avilaTek_app
